"""changed leaveBalances model

Revision ID: 3ccaee12737a
Revises: 9682757a54ef
Create Date: 2026-02-17 01:01:19.502123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccaee12737a'
down_revision: Union[str, Sequence[str], None] = '9682757a54ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('allocated_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('used_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_employee_leave_balance_year'), type_='unique')
        batch_op.create_index(batch_op.f('ix_leave_balances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_balances_leave_type_id'), ['leave_type_id'], unique=False)
        batch_op.create_unique_constraint('uq_employee_leave_year', ['employee_id', 'leave_type_id', 'year'])
        batch_op.drop_constraint(batch_op.f('leave_balances_leave_type_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('leave_balances_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'leave_types', ['leave_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('used')
        batch_op.drop_column('remaining')
        batch_op.drop_column('allocated')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('remaining', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('used', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leave_balances_employee_id_fkey'), 'employees', ['employee_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('leave_balances_leave_type_id_fkey'), 'leave_types', ['leave_type_id'], ['id'])
        batch_op.drop_constraint('uq_employee_leave_year', type_='unique')
        batch_op.drop_index(batch_op.f('ix_leave_balances_leave_type_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_leave_balances_company_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_employee_leave_balance_year'), ['employee_id', 'leave_type_id', 'year'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('used_days')
        batch_op.drop_column('allocated_days')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
