"""added and edited payroll models

Revision ID: 76f14c87470d
Revises: e1d4b5a5379a
Create Date: 2026-02-27 17:24:29.704930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76f14c87470d'
down_revision: Union[str, Sequence[str], None] = 'e1d4b5a5379a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    payroll_status_enum = postgresql.ENUM(
        "draft", "processing", "finalized", name="payroll_status_enum"
    )
    payroll_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('attendance_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leave_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_id', 'employee_id', name='uq_payroll_employee')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_payroll_id'), ['payroll_id'], unique=False)

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'processing', 'finalized', name='payroll_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('total_employees', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_employee_payroll'), type_='unique')
        batch_op.create_index(batch_op.f('ix_payrolls_company_id'), ['company_id'], unique=False)
        batch_op.create_unique_constraint('uq_company_year_month', ['company_id', 'year', 'month'])
        batch_op.drop_constraint(batch_op.f('payrolls_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('generated_at')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('net_salary')

    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('fixed_deductions', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('working_days_per_month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('effective_from', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('allowances',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_salary_structures_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_structures_employee_id'), ['employee_id'], unique=True)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('basic')
        batch_op.drop_column('deductions')
        batch_op.drop_column('hra')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hra', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deductions', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('basic', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_salary_structures_employee_id'))
        batch_op.drop_index(batch_op.f('ix_salary_structures_company_id'))
        batch_op.alter_column('allowances',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('effective_from')
        batch_op.drop_column('working_days_per_month')
        batch_op.drop_column('fixed_deductions')
        batch_op.drop_column('basic_salary')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gross_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payrolls_employee_id_fkey'), 'employees', ['employee_id'], ['id'])
        batch_op.drop_constraint('uq_company_year_month', type_='unique')
        batch_op.drop_index(batch_op.f('ix_payrolls_company_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_employee_payroll'), ['employee_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_net')
        batch_op.drop_column('total_deductions')
        batch_op.drop_column('total_gross')
        batch_op.drop_column('total_employees')
        batch_op.drop_column('status')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_payroll_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))

    op.drop_table('payslips')
    
        # drop ENUM type
    payroll_status_enum = postgresql.ENUM(
        "draft", "processing", "finalized", name="payroll_status_enum"
    )
    payroll_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
