"""updated to leavetype

Revision ID: 9682757a54ef
Revises: d652cfa9dcf6
Create Date: 2026-02-16 23:27:52.222553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9682757a54ef'
down_revision: Union[str, Sequence[str], None] = 'd652cfa9dcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_company_leave_code', ['company_id', 'code'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_company_leave_code', type_='unique')
        batch_op.drop_column('code')
        batch_op.drop_column('is_active')
        batch_op.drop_column('requires_approval')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
