"""added new constraint

Revision ID: beb4242b9ee4
Revises: 76f14c87470d
Create Date: 2026-02-27 23:49:26.322546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4242b9ee4'
down_revision: Union[str, Sequence[str], None] = '76f14c87470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_salary_effective', ['company_id', 'employee_id', 'effective_from'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_structures', schema=None) as batch_op:
        batch_op.drop_constraint('uq_salary_effective', type_='unique')

    # ### end Alembic commands ###
