"""updated attendance model

Revision ID: e1d4b5a5379a
Revises: 54a1a72f0015
Create Date: 2026-02-26 23:37:49.780351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d4b5a5379a'
down_revision: Union[str, Sequence[str], None] = '54a1a72f0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attendance_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_work_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('present', 'absent', 'on_leave', 'late', 'half_day', name='attendance_status_enum'),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_employee_attendance'), type_='unique')
        batch_op.create_index(batch_op.f('ix_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_unique_constraint('uq_employee_attendance_date', ['employee_id', 'attendance_date'])
        batch_op.drop_constraint(batch_op.f('attendances_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('total_hours')
        batch_op.drop_column('check_out')
        batch_op.drop_column('date')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendances_employee_id_fkey'), 'employees', ['employee_id'], ['id'])
        batch_op.drop_constraint('uq_employee_attendance_date', type_='unique')
        batch_op.drop_index(batch_op.f('ix_attendances_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_company_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_attendance_date'))
        batch_op.create_unique_constraint(batch_op.f('uq_employee_attendance'), ['employee_id', 'date'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('present', 'absent', 'on_leave', 'late', 'half_day', name='attendance_status_enum'),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_manual')
        batch_op.drop_column('total_work_minutes')
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('attendance_date')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
